### ISSUE TITLE
Error when trying to enable the importer addon in Blender 2.80

### ISSUE THREAD

**Issue by IonDworth** [thegoodhen/AprilTools#15]
When I try to enable the addon for importing the tracking data, Blender 2.80 throws this error:
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\apriltags_import.py", line 2, in <module>
    import numpy as np
  File "C:\Users\chris\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\chris\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 23, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application`
This also happens on Blender 2.81.

**Comment by thegoodhen** [comment]
Huh... Weird. I'll look into it.

**Comment by IonDworth** [comment]
I just realized it was because I had a bad version of numpy installed. I removed it and now it works.
